baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Research"
    url = "/research/"
    weight = 2

  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 3

  [[menu.main]]
    name = "CV"
    url = "/cv/"
    weight = 4

  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 5

  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 6
